name: isoxmlviz

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

#      - name: Run test suite
#        run: |
#          pipenv run test

      - name: Build package
        if: ${{ always() }}
        run: |
          pipenv run build_update
          pipenv run build

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: isoxmlviz
          path: ./**/dist/isoxmlviz-*.whl

